// Phaedrus-Vokabeln (Phädrus 1 & Phädrus 2)

const phaedrus1 = [
  { latin: "aliēnus, aliēna, aliēnum", deutsch: "fremd" },
  { latin: "bellum, bellī n", deutsch: "der Krieg" },
  { latin: "bōs, bovis m / f", deutsch: "der Ochse, das Rind" },
  { latin: "calamitās, calamitātis f", deutsch: "das Unglück, der Schaden" },
  { latin: "cōnspicere, cōnspiciō, cōnspexī", deutsch: "erblicken" },
  { latin: "contentus, contenta, contentum", deutsch: "zufrieden" },
  { latin: "cum", deutsch: "als (plötzlich), (zu der Zeit) als, (immer) wenn" },
  { latin: "esse, sum, fuī", deutsch: "sein, sich befinden" },
  { latin: "experīrī, experior, expertus sum", deutsch: "versuchen, ausprobieren, riskieren" },
  { latin: "ingēns, ingēns, ingēns (Gen. ingentis)", deutsch: "gewaltig, ungeheuer, riesig" },
  { latin: "iniūria, iniūriae f", deutsch: "das Unrecht, die Beleidigung" },
  { latin: "invidia, invidiae f", deutsch: "der Neid, der Hass" },
  { latin: "lātus, lāta, lātum", deutsch: "breit, weit" },
  { latin: "māior, māior, māius (Gen. māiōris)", deutsch: "größer" },
  { latin: "modus, modī m", deutsch: "die Art, die Weise; das Maß" },
  { latin: "movēre, moveō, mōvī, mōtum", deutsch: "bewegen, beeindrucken" },
  { latin: "noster, nostra, nostrum", deutsch: "unser" },
  { latin: "ōs, ōris n", deutsch: "der Mund, das Gesicht" },
  { latin: "patī, patior, passus sum", deutsch: "leiden, erleiden, ertragen; zulassen" },
  { latin: "potēns, potēns, potēns (Gen. potentis)", deutsch: "mächtig, einflussreich, stark" },
  { latin: "potius Adv.", deutsch: "eher, lieber" },
  { latin: "prius Adv.", deutsch: "früher, zuerst" },
  { latin: "quaerere, quaerō, quaesīvī, quaesītum", deutsch: "suchen, untersuchen; erwerben, anstreben; fragen; (ex / dē m. Abl.) (jdn.) fragen" },
  { latin: "querī, queror, questus sum (m. Akk.)", deutsch: "klagen, sich beklagen (über)" },
  { latin: "quis?", deutsch: "wer?" },
  { latin: "quondam Adv.", deutsch: "einst, einmal; manchmal" },
  { latin: "rāna", deutsch: "der Frosch" },
  { latin: "repellere, repellō, reppulī, repulsum", deutsch: "zurückstoßen, vertreiben" },
  { latin: "sēdēs, sēdis f", deutsch: "der Wohnsitz; der Platz, der Sitz" },
  { latin: "similis, similis, simile (m. Gen./Dat.)", deutsch: "ähnlich" },
  { latin: "statim Adv.", deutsch: "sofort, auf der Stelle" },
  { latin: "sustinēre, sustineō", deutsch: "standhalten; aushalten, ertragen" },
  { latin: "trīstis, trīstis, trīste", deutsch: "traurig; unfreundlich" },
  { latin: "velle, volō, voluī", deutsch: "wollen" },
  { latin: "vidēre, videō, vīdī", deutsch: "sehen; darauf achten" },
  { latin: "vītāre, vītō, vītāvī, vītātum", deutsch: "meiden, vermeiden" },
  { latin: "vōs Nom.", deutsch: "ihr" },
  { latin: "vōx, vōcis f", deutsch: "die Stimme, die Äußerung, der Laut" },
  { latin: "vultus, vultūs m", deutsch: "das Gesicht, der Gesichtsausdruck" },
  { latin: "āles", deutsch: "der Vogel" },
  { latin: "arbor, arboris f", deutsch: "der Baum" },
  { latin: "bonus, bona, bonum", deutsch: "gut" },
  { latin: "dum", deutsch: "während, solange, (so lange) bis" },
  { latin: "fābula, fābulae f", deutsch: "die Geschichte, die Erzählung, das Theaterstück" },
  { latin: "habēre, habeō", deutsch: "haben, halten" },
  { latin: "in Präp. m. Abl.", deutsch: "in, auf, bei (wo?)" },
  { latin: "laudāre, laudō", deutsch: "loben" },
  { latin: "mōns, montis m", deutsch: "der Berg" },
  { latin: "nōn", deutsch: "nicht" },
  { latin: "ostendere, ostendō, ostendī", deutsch: "zeigen, erklären" },
  { latin: "placēre, placeō", deutsch: "gefallen" },
  { latin: "quam", deutsch: "als, wie" },
  { latin: "sedēre, sedeō", deutsch: "sitzen" },
  { latin: "sentīre, sentiō, sēnsī", deutsch: "fühlen, meinen, wahrnehmen" },
  { latin: "sī", deutsch: "wenn, falls" },
  { latin: "tibi Dat. von tū", deutsch: "dir" },
  { latin: "an", deutsch: "ob (nicht), im indirekten Fragesatz" },
  { latin: "corpus, corporis n", deutsch: "der Körper, der Leichnam" },
  { latin: "cutis, cutis", deutsch: "die Haut" },
  { latin: "dīcere, dīcō, dīxī", deutsch: "sagen, sprechen" },
  { latin: "et", deutsch: "und, auch" },
  { latin: "iacēre, iaceō, iacuī", deutsch: "liegen" },
  { latin: "ille, illa, illud (Gen. illīus, Dat. illī)", deutsch: "jener, jene, jenes" },
  { latin: "imitārī", deutsch: "nachahmen" },
  { latin: "indīgnātus, a, um", deutsch: "empört" },
  { latin: "īnflāre", deutsch: "aufblasen" },
  { latin: "inops", deutsch: "ein Schwacher" },
  { latin: "intendere (Perf. intendī)", deutsch: "aufblähen" },
  { latin: "interrogāre → rogāre", deutsch: "fragen" },
  { latin: "magnitūdō, magnitūdinis f", deutsch: "die Größe" },
  { latin: "nātus, nātī m", deutsch: "das Kind" },
  { latin: "negāre, negō, negāvī", deutsch: "leugnen, verneinen, ablehnen" },
  { latin: "nīsus, nīsūs", deutsch: "die Anstrengung" },
  { latin: "novissimē", deutsch: "zuletzt" },
  { latin: "pellis, is f", deutsch: "die Haut" },
  { latin: "perīre, pereō, periī", deutsch: "umkommen, sterben" },
  { latin: "prātum, prātī n", deutsch: "die Wiese" },
  { latin: "rogāre, rogō", deutsch: "bitten, fragen" },
  { latin: "rūgōsus, a, um", deutsch: "runzlig" },
  { latin: "rumpere, rumpō, rūpī, ruptum", deutsch: "platzen" },
  { latin: "rūrsus Adv.", deutsch: "wieder, noch einmal" },
  { latin: "sē Akk. (sēsē = sē)", deutsch: "sich" },
  { latin: "suus, sua, suum", deutsch: "ihr, sein" },
  { latin: "tācta ~ mōta", deutsch: "im PDF ohne eigene Übersetzung angegeben" },
  { latin: "tantus, tanta, tantum", deutsch: "so groß, so viel" },
  { latin: "tum Adv.", deutsch: "dann, damals, da" },
  { latin: "validus, a, um", deutsch: "stark" },
  { latin: "ā / ab Präp. m. Abl.", deutsch: "von, von … her" },
  { latin: "ad Präp. m. Akk.", deutsch: "zu, bei, nach" },
  { latin: "Aesōpus, Aesōpī m", deutsch: "Äsop (griechischer Fabeldichter; Vorbild für Phädrus)" },
  { latin: "agere, agō, ēgī, āctum", deutsch: "handeln, tun; treiben; verhandeln" },
  { latin: "bonum, bonī n", deutsch: "das Gut, das Gute" },
  { latin: "contumēlia", deutsch: "die schmachvolle Behandlung" },
  { latin: "dare, dō, dedī", deutsch: "geben" },
  { latin: "dēgere ~ agere", deutsch: "—" },
  { latin: "dēspicere (Perf. dēspēxī)", deutsch: "verachten" },
  { latin: "ex / ē Präp. m. Abl.", deutsch: "aus, von … her" },
  { latin: "exemplum, exemplī n", deutsch: "das Beispiel, das Vorbild" },
  { latin: "genus, generis n", deutsch: "das Geschlecht, die Art, die Abstammung" },
  { latin: "glōriārī (m. Abl.)", deutsch: "sich rühmen (wegen)" },
  { latin: "grāculus", deutsch: "die Dohle" },
  { latin: "habitus, habitūs m", deutsch: "die Gewohnheit" },
  { latin: "hic, haec, hoc (Gen. huius, Dat. huic)", deutsch: "dieser, diese, dieses (hier)" },
  { latin: "incipere, incipiō, coepī (incēpī)", deutsch: "beginnen, anfangen" },
  { latin: "libet", deutsch: "es gefällt" },
  { latin: "maerēns", deutsch: "traurig" },
  { latin: "male mulcātus", deutsch: "übel zugerichtet" },
  { latin: "nātūra, nātūrae f", deutsch: "die Natur, das Wesen, die Beschaffenheit" },
  { latin: "nē", deutsch: "dass nicht, damit nicht" },
  { latin: "nec", deutsch: "und nicht, auch nicht, nicht einmal" },
  { latin: "nec … nec", deutsch: "weder … noch" },
  { latin: "nōbīs Dat. von nōs", deutsch: "uns" },
  { latin: "prōdere, prōdō, prōdidī, prōditum", deutsch: "überliefern, verraten" },
  { latin: "proprius, a, um", deutsch: "eigen" },
  { latin: "-que", deutsch: "nachgestellt: und" },
  { latin: "quī, quae, quod", deutsch: "welcher, welche, welches; der, die, das" },
  { latin: "quīdam, quaedam, quiddam subst.", deutsch: "ein gewisser, (irgend)einer; Pl. einige" },
  { latin: "redīre, redeō, rediī", deutsch: "zurückkehren" },
  { latin: "repulsa", deutsch: "Substantiv zu repellere" },
  { latin: "trīstis nota", deutsch: "die bittere Beschimpfung" },
  { latin: "tua calamitās", deutsch: "du in deinem Unglück" },
  { latin: "at", deutsch: "aber, dagegen, jedoch" },
  { latin: "cāseus", deutsch: "der Käse" },
  { latin: "corvus, corvī m", deutsch: "der Rabe" },
  { latin: "decor, decōris", deutsch: "der Schmuck" },
  { latin: "ē-mittere", deutsch: "herauslassen, ausstoßen" },
  { latin: "etiam", deutsch: "auch, sogar" },
  { latin: "gerere, gerō", deutsch: "tragen, führen, ausführen" },
  { latin: "mittere, mittō, mīsī, missum", deutsch: "schicken; werfen" },
  { latin: "nitor", deutsch: "der Glanz" },
  { latin: "nūlla prior āles foret", deutsch: "kein Vogel wäre dir überlegen" },
  { latin: "pinna", deutsch: "die Feder" },
  { latin: "quantus, quanta, quantum", deutsch: "wie groß, wie viel" },
  { latin: "quī", deutsch: "wie wunderbar" },
  { latin: "tuus, tua, tuum", deutsch: "dein" }
];

const phaedrus2 = [
  { latin: "canis, canis", deutsch: "der Hund" },
  { latin: "cibus, cibī m", deutsch: "die Nahrung, die Speise, das Essen" },
  { latin: "condiciō, condiciōnis f", deutsch: "die Bedingung, die Lage; die Umstände" },
  { latin: "cūstōs, cūstōdis m/f", deutsch: "der Wächter, die Wächterin" },
  { latin: "famēs, famis", deutsch: "der Hunger" },
  { latin: "gaudēre, gaudeō", deutsch: "sich freuen; mit Abl. sich freuen über etwas" },
  { latin: "lībertās, lībertātis f", deutsch: "die Freiheit" },
  { latin: "lupus, lupī", deutsch: "der Wolf" },
  { latin: "occurrere, occurrō, occurrī", deutsch: "entgegentreten, begegnen" },
  { latin: "officium, officiī n", deutsch: "der Dienst, die Pflicht, das Pflichtgefühl" },
  { latin: "praestāre, praestō, praestitī", deutsch: "mit Akk. zeigen, beweisen; garantieren; mit Dat. (jdn.) übertreffen" },
  { latin: "silva, silvae f", deutsch: "der Wald" },
  { latin: "sub Präp. m. Abl.", deutsch: "unter, unten an, unten bei (wo?)" },
  { latin: "tēctum, tēctī n", deutsch: "das Dach, das Haus" },
  { latin: "tuērī, tueor m. Akk.", deutsch: "betrachten; schützen, sorgen für" },
  { latin: "amīcus, amīcī m", deutsch: "der Freund" },
  { latin: "brevis, brevis, breve", deutsch: "kurz" },
  { latin: "dominus, dominī m", deutsch: "der Herr, der Hausherr" },
  { latin: "domus, domūs f", deutsch: "das Haus" },
  { latin: "facilis, facilis, facile", deutsch: "leicht, einfach" },
  { latin: "fortis, fortis, forte", deutsch: "mutig, tapfer, stark" },
  { latin: "labōrāre, labōrō", deutsch: "arbeiten, sich anstrengen" },
  { latin: "loquī, loquor, locūtus sum", deutsch: "reden, sprechen" },
  { latin: "multus, multa, multum", deutsch: "viel" },
  { latin: "nivēs imbrēsque", deutsch: "Schnee und Regen" },
  { latin: "resistere, resistō, restitī", deutsch: "Widerstand leisten; stehen bleiben" },
  { latin: "tempus, temporis n", deutsch: "die Zeit, die Umstände" },
  { latin: "ut Subj. m. Ind.", deutsch: "sobald, sooft" },
  { latin: "ut Subj. m. Konj.", deutsch: "dass, sodass, damit; um … zu" },
  { latin: "vīta, vītae f", deutsch: "das Leben, die Lebensweise" },
  { latin: "vītam agere", deutsch: "das Leben verbringen" },
  { latin: "aut", deutsch: "oder" },
  { latin: "deinde Adv.", deutsch: "dann, darauf" },
  { latin: "dulcis, dulcis, dulce", deutsch: "süß, angenehm" },
  { latin: "egō Nom.", deutsch: "ich" },
  { latin: "facere, faciō, fēcī, factum", deutsch: "machen, tun, handeln; mit doppeltem Akk. machen zu" },
  { latin: "forte Adv.", deutsch: "zufällig" },
  { latin: "fūr, fūris m/f", deutsch: "der Dieb, die Diebin" },
  { latin: "īdem, eadem, idem (Gen. eiusdem, Dat. eīdem)", deutsch: "derselbe, dieselbe, dasselbe; der (die, das) gleiche" },
  { latin: "inquam, 3. Pers. Sg. inquit", deutsch: "sage ich, sagte ich" },
  { latin: "invicem", deutsch: "gegenseitig" },
  { latin: "līmen, līminis n", deutsch: "der Hauseingang" },
  { latin: "longē Adv.", deutsch: "bei Weitem" },
  { latin: "maciē cōnfectus", deutsch: "abgemagert" },
  { latin: "nitēre", deutsch: "wohlgenährt aussehen" },
  { latin: "noctū", deutsch: "nachts" },
  { latin: "pār, pār, pār (Gen. paris)", deutsch: "gleich, ebenbürig" },
  { latin: "perpāstus", deutsch: "wohlgenährt" },
  { latin: "posse, possum, potuī", deutsch: "können" },
  { latin: "prōloquī", deutsch: "vortragen" },
  { latin: "quaesō", deutsch: "bitte!" },
  { latin: "salūtāre", deutsch: "grüßen" },
  { latin: "sīc Adv.", deutsch: "so" },
  { latin: "simpliciter Adv.", deutsch: "schlicht" },
  { latin: "unde Adv.", deutsch: "woher" },
  { latin: "asper, aspera, asperum", deutsch: "rau" },
  { latin: "ergō Adv.", deutsch: "also, deshalb" },
  { latin: "mēcum (~ cum mē)", deutsch: "mit mir" },
  { latin: "mihi Dat. von egō", deutsch: "mir" },
  { latin: "nunc Adv.", deutsch: "jetzt, nun" },
  { latin: "ōtiōsum largō satiārī cibō", deutsch: "in Ruhe von reichlicher Speise satt werden" },
  { latin: "parātus, parāta, parātum (ad m. Akk.)", deutsch: "bereit, entschlossen (zu / für)" },
  { latin: "trahere, trahō, trāxī, tractum", deutsch: "ziehen, schleppen" },
  { latin: "venīre, veniō, vēnī", deutsch: "kommen" },
  { latin: "vērō Adv.", deutsch: "in der Tat, wirklich; aber" },
  { latin: "vīvere, vīvō", deutsch: "leben" }
];

// Auch window-Fallbacks setzen, falls kein ES-Module genutzt wird
if (typeof window !== 'undefined') {
  window.phaedrus1 = phaedrus1;
  window.phaedrus2 = phaedrus2;
}

export { phaedrus1, phaedrus2 };